swipe:
  3:
    left:
      command: "xdotool key alt+Right" # History forward 
    right:
      command: "xdotool key alt+Left" # History back
    up:
      command: "xdotool key super+f" # fullscreentoggle 
    down:
      command: "xdotool key super+f" # fullscreentoggle
