swipe:
  3:
    left:
      command: "xdotool key alt+Left" # History forward 
    right:
      command: "xdotool key alt+Right" # History back
    up:
      command: "xdotool key super+f" # fullscreentoggle 
    down:
      command: "xdotool key super+f" # fullscreentoggle
  4:
    left:
      command: "xdotool key super+shift+Tab" # previous workspace
    right:
      command: "xdotool key super+Tab" # next workspace
      

